### ISSUE TITLE
data is too long

### ISSUE THREAD

**Issue by qbarbier** [RGLab/openCyto#166] opened 2018-01-30 11:00 UTC
Hello,

I run openCyto's gating on multiple file and i don't know why, but sometime, one file cannot gated and i have this error message returned 
` Vi (i = file number) : data is too long.`

I reject this data from my flowSet and the gates successful.

Do you know why there are message error ? Because i open data in my R and i don't see any problem about data value.

Best regard

**Comment by malisas** [comment] 2018-04-12 19:59
I also ran into this error just now when using `gate_flowClust_2d`.
```
Using the serial version of flowClust
Error in matrix(ecol, length(include)) : data is too long
```

**Comment by mikejiang** [comment] 2018-04-12 20:28
Can you provide a minimum reproducible example?I'd like to see if we can generate a more meaningful message at least

**Comment by bc2zb** [comment] 2018-04-12 20:42
I'm trying to do so now, but it's really odd. If I subset this flowFrame, the error's appearance appears to occur only when using certain subsets of the frame.

flow_frame[c(1:5000),] doesn't work
flow_frame[c(3999:4999),] doesn't work

flow_frame[c(1:4999),] does work
flow_frame[c(2:5000),] does work
flow_frame[c(3000:4000),] does work

[troublesome_ff.Rdata.zip](https://github.com/RGLab/openCyto/files/1904902/troublesome_ff.Rdata.zip)

**Comment by malisas** [comment] 2018-04-12 21:48
I also experience the same odd subsetting behavior on my own data as @bc2zb mentioned.

If I change the number of clusters `K` from 2 to 1, it work fine. `gate_flowClust_2d` [calls](https://github.com/RGLab/openCyto/blob/76e6c13e4dccb9050a9b2aec41935439e518c593/R/gating-functions.R#L433)  `getEllipseGate`, which [uses](https://github.com/RGLab/openCyto/blob/cc3d8565c972eb0b5308cafb8aa219a40b83a7ec/R/functions.R#L125) `K` to define the `include` parameter (in the Error message).

**Comment by gfinak** [comment] 2018-04-13 14:56
For the record, I tried to reproduce this error with your data and do not have the same problem.
```

**Comment by bc2zb** [comment] 2018-04-13 15:08
Well, that's unfortunate. Right now, I'm just skipping files where this happens. If I figure out a more reproducible example, I'll let you know. Our session_info() appears mostly identical, so it must be something weird in my specific computer.  Thanks for checking.

**Comment by gfinak** [comment] 2018-04-13 15:09
I'm a bit concerned that both you and @malisas report seeing this... we'll keep the issue open and keep an eye on it. Thanks for contributing.

**Comment by DamienSTI** [comment] 2018-09-26 14:47
I have the same problem while looping through different flowFrames.
In some instances, flowClust.2d passes through but blocks on others returning:
"Error in matrix(ecol, length(include)) : data is too long"

I noticed that specifying the K argument may induce the same error while the function would run properly through the same flowFrame using default arguments (see below).

> Morpho_gate <- flowClust.2d(fr = f, xChannel = "FSC-H", yChannel = "SSC-H")
The prior specification has no effect when usePrior=no
Using the serial version of flowClust
> Morpho_gate <- flowClust.2d(fr = f, xChannel = "FSC-H", yChannel = "SSC-H", K=3)
The prior specification has no effect when usePrior=no
Using the serial version of flowClust
Error in matrix(ecol, length(include)) : data is too long

Hope this helps.

**Comment by feltzmc** [comment] 2018-10-10 20:12
Not sure if it will help track this issue down but I just got following error while attempting to tailgate for live cells:

Error in matrix(ecol, length(include)) : data is too long
Calls: gating ... .gating_gtMethod -> eval -> eval -> mapply -> <Anonymous>
In addition: Warning message:
did not converge in 100 iterations

Interestingly if I set the tol=0.75, the gating finishes with no issues.  If I set it for 0.9 or above, it errors on the second file (out of 17).

**Comment by kdh4win4** [comment] 2018-10-24 19:00
I have exactly the same issue now. 
I am checking all packages related and data files too.

**Comment by cmartinezfleites** [comment] 2019-05-22 11:34
I have the same issue:

> sessionInfo()
R version 3.6.0 (2019-04-26)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 17134)

Matrix products: default

locale:
[1] LC_COLLATE=English_United Kingdom.1252  LC_CTYPE=English_United Kingdom.1252   
[3] LC_MONETARY=English_United Kingdom.1252 LC_NUMERIC=C                           
[5] LC_TIME=English_United Kingdom.1252    

attached base packages:
[1] grid      parallel  stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] Rgraphviz_2.29.0            graph_1.63.0                BiocGenerics_0.31.2        
 [4] kohonen_3.0.8               ConsensusClusterPlus_1.49.0 Rtsne_0.15                 
 [7] FlowSOM_1.15.1              igraph_1.2.4.1              ggridges_0.5.1             
[10] purrr_0.3.2                 dplyr_0.8.1                 RColorBrewer_1.1-2         
[13] hash_2.2.6.1                readxl_1.3.1                knitr_1.23                 
[16] data.table_1.12.2           flowTrans_1.37.0            flowClust_3.23.0           
[19] flowViz_1.49.0              lattice_0.20-38             flowStats_3.43.3           
[22] cluster_2.0.9               ggcyto_1.13.2               ggplot2_3.1.1              
[25] openCyto_1.23.3             flowWorkspace_3.33.2        ncdfFlow_2.31.0            
[28] BH_1.69.0-1                 RcppArmadillo_0.9.400.3.0   flowCore_1.51.3            

loaded via a namespace (and not attached):
 [1] Biobase_2.45.0      splines_3.6.0       R.utils_2.8.0       ellipse_0.4.1       gtools_3.8.1       
 [6] RcppParallel_4.4.2  assertthat_0.2.1    highr_0.8           stats4_3.6.0        latticeExtra_0.6-28
[11] RBGL_1.61.0         cellranger_1.1.0    robustbase_0.93-5   pillar_1.4.0        glue_1.3.1         
[16] digest_0.6.19       colorspace_1.4-1    Matrix_1.2-17       R.oo_1.22.0         plyr_1.8.4         
[21] pcaPP_1.9-73        XML_3.98-1.19       pkgconfig_2.0.2     tsne_0.1-3          fda_2.4.8          
[26] zlibbioc_1.31.0     corpcor_1.6.9       mvtnorm_1.0-10      scales_1.0.0        tibble_2.1.1       
[31] withr_2.1.2         hexbin_1.27.3       lazyeval_0.2.2      mnormt_1.5-5        magrittr_1.5       
[36] crayon_1.3.4        IDPmisc_1.1.19      mclust_5.4.3        ks_1.11.5           R.methodsS3_1.7.1  
[41] MASS_7.3-51.4       tools_3.6.0         matrixStats_0.54.0  stringr_1.4.0       munsell_0.5.0      
[46] packrat_0.5.0       compiler_3.6.0      rlang_0.3.4         rstudioapi_0.10     gtable_0.3.0       
[51] rrcov_1.4-7         R6_2.4.0            gridExtra_2.3       clue_0.3-57         KernSmooth_2.23-15 
[56] stringi_1.4.3       Rcpp_1.0.1          DEoptimR_1.0-8      tidyselect_0.2.5    xfun_0.7

**Comment by jacobpwagner** [comment] 2019-05-22 17:43
@bc2zb , I can reproduce your error and I'm working on a fix to that issue for `gate_flowClust_2d` now. @feltzmc , the problem will probably be very similar for your `tailgate` issue and will likely have a similar solution.

**Comment by jacobpwagner** [comment] 2019-05-23 17:53
@gfinak , I think this may actually be a `flowClust` issue. I've included a reproducible example below and explanation of why I think that may be the case. Any insight you could provide would be much appreciated.

Using the example and data from @bc2zb, I can reproduce the error with certain PRNG seeds. For example, this will fail:
``` r
load("troublesome_ff.Rdata")
set.seed(5)
nondebris_gate <- gate_mindensity(flow_frame, "FSC-A")
# split flow_frame into positive and negative frames
nondebris_set <- split(flow_frame,
                       flowCore::filter(flow_frame, nondebris_gate))
# beads and cells have different responses to this gate, grab whichever has the higher number of events
num_pos_events <- nrow(nondebris_set$`+`)
num_neg_events <- nrow(nondebris_set$`-`)
if(num_pos_events > num_neg_events){
  nondebris_frame <- nondebris_set$`+`
}else{
  nondebris_frame <- nondebris_set$`-`
}
# gate singlets
singlets_gate <- gate_singlet(nondebris_frame, maxit = 20, wider_gate = T)
singlets_set <- split(nondebris_frame,
                      flowCore::filter(nondebris_frame, singlets_gate))
# retrive singlets only
singlets_frame <- singlets_set$`singlet+`
# perform ellipsoid gating to tighten up population
ellipsoid_gate <- gate_flowClust_2d(singlets_frame,
                                    xChannel = "FSC-A",
                                    yChannel = "SSC-A")
```
If you change the `set.seed` line to `set.seed(1)`, it will succeed. The error is arising from line 143 in `functions.R`:
```
ecol <- matrix(ecol, length(include))
```
where `length(include)` is getting a value of 0. This error looks like https://github.com/RGLab/flowCore/issues/96 because it's a base R error, but is probably unrelated. If you trace that back, it is arising because at line 433 in `gating-functions.R`, the call to `flowClust` is not generating an error, but is yielding nothing but NaN values in all of the slots of the object it returns (`tmix_results`):
``` r
  tmix_results <- flowClust(fr, varNames = c(xChannel, yChannel)
                                , K = K, trans = trans
                                , usePrior = usePrior
                                , prior = prior
                                , min.count = min.count, max.count = max.count
                                , nstart = nstart
                                , ...)
```
The issue can in turn be traced to the initial labeling of clusters by `kmeans` at line 567 in `flowClust.R`:
```
label<-try(kmeans(scale(y),K[i],nstart=nstart,iter.max=100,algorithm="MacQueen")$cluster,silent=TRUE)
``` 
This is where the seed finally comes in, as it determines the random rows chosen for the initial centers for `kmeans`. It appears that the difference between the failing and succeeding cases is simply the way those initial labels come out of `kmeans`. The clusters are actually the same, but with their labels inverted (1 vs 2). Swapping the 1s to 2s and 2s to 1s after that line will actually convert the failing case to succeeding and succeeding case to failing.

These inverted labels then change the result from `flowClust` in `flowClust.c`, and the `status2` flag in that code weirdly ends up 1 in the succeeding case but 0 in the failing case. I can continue looking for where the label inversion causes this issue in `flowClust.c`, but I thought @gfinak may have more immediate insight as it seems very strange that the function would fail/succeed on isomorphic clustering problems with the labels swapped.

**Comment by jacobpwagner** [comment] 2019-05-23 18:04
Also, I can of course always add a check/guard for that line in the failing case so it produces a more helpful error. I just wanted to investigate the root cause for the discrepancy. 

@feltzmc , I'm looking in to the similar error for `tailgate`, but if you could provide the data and code that are bringing about the error that would help me run it down.

**Comment by jacobpwagner** [comment] 2019-05-23 19:25
@bc2zb , for now you could try setting a nonzero value to the `randomStart` argument in your `gate_flowClust_2d` call to use the best of a number of random samples instead. That will bypass the `kmeans` initialization labels. Given the nature of the initial labeling issue, I don't yet see why that should solve the problem (as I don't know why the `kmeans` labels should be worse) and you may still see this error from some samples. However, it did allow the failing cases in my testing to complete successfully.

That's definitely a temporary possible fix, but it might work until I figure this out.

**Comment by feltzmc** [comment] 2019-05-29 14:50
@jacobpwagner Thanks for tracking this down, I don't remember which data set was producing this error but if I run into it again I will let you know.

**Comment by jacobpwagner** [comment] 2019-05-29 18:04
I'm looping back to this and digging in to `flowClust.C`. Sure enough, it seems like the `status2` flag isn't getting set in the failing case, which is letting the solver pass its proper termination point. It seems to be following the same trajectory in both cases except for the one extra (bad) iteration, but the inverted labels must cause some issue in either the `up_date_precision` or `ECMUpdateSigmaG2` functions.

[progress_log.txt](https://github.com/RGLab/openCyto/files/3233809/progress_log.txt)

**Comment by jacobpwagner** [comment] 2019-05-30 18:30
https://github.com/RGLab/flowClust/commit/af7df87d7f81081dbdc65ab63ae86a2d9bf994d0 should fix this and ensure that the iterative solver stops as soon as it encounters a problem so you should not run in to that error. Thanks @bc2zb for your data and example as it really helped in tracking down the bug.

If anyone else here who was getting the error from a `flowClust` call could check to see if the commit fixes the problem and report back, that would be much appreciated. I will still look in to the issue for `tailgate`.

**Comment by jacobpwagner** [comment] 2020-04-21 19:46
I believe this was resolved by the `flowClust` repair and there have been no replies with continued problems after that, so I'm going ahead and closing it.

**Closed by jacobpwagner** 2020-04-21 19:46 UTC
